#!/bin/bash

# Создание базы данных и бэкап

prog="${0##*/}"

if [ $# -lt 3 ]; then
    echo "$prog: usage $prog username dbname dump.backup"
    exit 1
fi

if [ ! \( -f "$3" \) ]; then
   echo "файл backup не найден"
   exit 1
fi

su $1 -c "createdb $2"

if [ "$?" -ne 0 ]; then
   exit 1
fi

pg_restore -U "$1" -d "$2" -1 "$3" 2> error

if [ "$?" -eq 0 ]; then
  echo "создание БД прошло успешно: user $1, db $2, table dot"
else
  echo "нужно исправить ошибки, error file"
fi
